country_list = [u"Andorra",
                u"United Arab Emirates",
                u"Afghanistan",
                u"Antigua and Barbuda",
                u"Anguilla",
                u"Albania",
                u"Armenia",
                u"Angola",
                u"Antarctica",
                u"Argentina",
                u"American Samoa",
                u"Austria",
                u"Australia",
                u"Aruba",
                u"Azerbaijan",
                u"Bosnia and Herzegovina",
                u"Barbados",
                u"Bangladesh",
                u"Belgium",
                u"Burkina Faso",
                u"Bulgaria",
                u"Bahrain",
                u"Burundi",
                u"Benin",
                u"Bermuda",
                u"Brunei Darussalam",
                u"Bolivia, Plurinational State of",
                u"Brazil",
                u"Bahamas",
                u"Bhutan",
                u"Bouvet Island",
                u"Botswana",
                u"Belarus",
                u"Belize",
                u"Canada",
                u"Cocos (Keeling) Islands",
                u"Congo, Democratic Republic of the",
                u"Central African Republic",
                u"Congo",
                u"Switzerland",
                u"Cook Islands",
                u"Chile",
                u"Cameroon",
                u"China",
                u"Colombia",
                u"Costa Rica",
                u"Cuba",
                u"Cabo Verde",
                u"Christmas Island",
                u"Cyprus",
                u"Czech Republic",
                u"Germany",
                u"Djibouti",
                u"Denmark",
                u"Dominica",
                u"Dominican Republic",
                u"Algeria",
                u"Ecuador",
                u"Estonia",
                u"Egypt",
                u"Western Sahara",
                u"Eritrea",
                u"Spain",
                u"Ethiopia",
                u"Finland",
                u"Fiji",
                u"Falkland Islands (Malvinas)",
                u"Micronesia, Federated States of",
                u"Faroe Islands",
                u"France",
                u"Gabon",
                u"United Kingdom",
                u"Grenada",
                u"Georgia",
                u"French Guiana",
                u"Guernsey",
                u"Ghana",
                u"Gibraltar",
                u"Greenland",
                u"Gambia",
                u"Guinea",
                u"Guadeloupe",
                u"Equatorial Guinea",
                u"Greece",
                u"South Georgia and the South Sandwich Islands",
                u"Guatemala",
                u"Guam",
                u"Guinea-Bissau",
                u"Guyana",
                u"Hong Kong",
                u"Heard Island and McDonald Islands",
                u"Honduras",
                u"Croatia",
                u"Haiti",
                u"Hungary",
                u"Indonesia",
                u"Ireland",
                u"Israel",
                u"Isle of Man",
                u"India",
                u"British Indian Ocean Territory",
                u"Iraq",
                u"Iran, Islamic Republic of",
                u"Iceland",
                u"Italy",
                u"Jersey",
                u"Jamaica",
                u"Jordan",
                u"Japan",
                u"Kenya",
                u"Kyrgyzstan",
                u"Cambodia",
                u"Kiribati",
                u"Comoros",
                u"Saint Kitts and Nevis",
                u"Korea, Democratic People's Republic of",
                u"Korea, Republic of",
                u"Kuwait",
                u"Cayman Islands",
                u"Kazakhstan",
                u"Lao People's Democratic Republic",
                u"Lebanon",
                u"Saint Lucia",
                u"Liechtenstein",
                u"Sri Lanka",
                u"Liberia",
                u"Lesotho",
                u"Lithuania",
                u"Luxembourg",
                u"Latvia",
                u"Libya",
                u"Morocco",
                u"Monaco",
                u"Moldova, Republic of",
                u"Montenegro",
                u"Saint Martin (French part)",
                u"Madagascar",
                u"Marshall Islands",
                u"Macedonia, the former Yugoslav Republic of",
                u"Mali",
                u"Myanmar",
                u"Mongolia",
                u"Macao",
                u"Northern Mariana Islands",
                u"Martinique",
                u"Mauritania",
                u"Montserrat",
                u"Malta",
                u"Mauritius",
                u"Maldives",
                u"Malawi",
                u"Mexico",
                u"Malaysia",
                u"Mozambique",
                u"Namibia",
                u"New Caledonia",
                u"Niger",
                u"Norfolk Island",
                u"Nigeria",
                u"Nicaragua",
                u"Netherlands",
                u"Norway",
                u"Nepal",
                u"Nauru",
                u"Niue",
                u"New Zealand",
                u"Oman",
                u"Panama",
                u"Peru",
                u"French Polynesia",
                u"Papua New Guinea",
                u"Philippines",
                u"Pakistan",
                u"Poland",
                u"Saint Pierre and Miquelon",
                u"Pitcairn",
                u"Puerto Rico",
                u"Palestine, State of",
                u"Portugal",
                u"Palau",
                u"Paraguay",
                u"Qatar",
                u"Romania",
                u"Serbia",
                u"Russian Federation",
                u"Rwanda",
                u"Saudi Arabia",
                u"Solomon Islands",
                u"Seychelles",
                u"Sudan",
                u"Sweden",
                u"Singapore",
                u"Saint Helena, Ascension and Tristan da Cunha",
                u"Slovenia",
                u"Svalbard and Jan Mayen",
                u"Slovakia",
                u"Sierra Leone",
                u"San Marino",
                u"Senegal",
                u"Somalia",
                u"Suriname",
                u"Sao Tome and Principe",
                u"El Salvador",
                u"Syrian Arab Republic",
                u"Swaziland",
                u"Turks and Caicos Islands",
                u"Chad",
                u"French Southern Territories",
                u"Togo",
                u"Thailand",
                u"Tajikistan",
                u"Tokelau",
                u"Timor-Leste",
                u"Turkmenistan",
                u"Tunisia",
                u"Tonga",
                u"Turkey",
                u"Trinidad and Tobago",
                u"Tuvalu",
                u"Taiwan, Province of China",
                u"Tanzania, United Republic of",
                u"Ukraine",
                u"Uganda",
                u"United States Minor Outlying Islands",
                u"United States",
                u"Uruguay",
                u"Uzbekistan",
                u"Holy See",
                u"Saint Vincent and the Grenadines",
                u"Venezuela, Bolivarian Republic of",
                u"Virgin Islands, British",
                u"Virgin Islands, U.S.",
                u"Viet Nam",
                u"Vanuatu",
                u"Wallis and Futuna",
                u"Samoa",
                u"Yemen",
                u"Mayotte",
                u"South Africa",
                u"Zambia",
                u"Zimbabwe",
                ]
